export const asidePersons = {
    allLight: [
        { id: 1, pass: 'humans', rase: 'Humans' },
        { id: 2, pass: 'lwizards', rase: 'Light Wizards' },
        { id: 3, pass: 'elves', rase: 'Elves' },
        { id: 4, pass: 'dwarves', rase: 'Dwarves' },
        { id: 5, pass: 'hobbits', rase: 'Hobbits' },
        { id: 6, pass: 'ents', rase: 'Ents' },
    ],
    allDark: [
        { id: 1, pass: 'orcs', rase: 'Orcs' },
        { id: 2, pass: 'goblins', rase: 'Goblins' },
        { id: 3, pass: 'trolls', rase: 'Trolls' },
        { id: 4, pass: 'uruks', rase: 'Uruk-hais' },
        { id: 5, pass: 'dwizards', rase: 'Dark Wizards' },
        { id: 6, pass: 'beasts', rase: 'Beasts' },
    ],
};

export const charactersTest = [
    {
        id: 1,
        race: 'human',
        person: 'Aragorn II',
        warPic: 'aragorn',
        to1: `/Lotr1`,
        movie1: 'The Fellowship of the Ring (2001)',
        to2: `/Lotr2`,
        movie2: 'The Two Towers (2002)',
        to3: `/Lotr3`,
        movie3: 'The Return of the King (2003)',
        to4: ``,
        movie4: ``,
        to5: ``,
        movie5: ``,
        to6: ``,
        movie6: ``,
        to7: ``,
        movie7: ``,
        h4: `Elessar ("Elfstone"), Telcontar ("Strider"),
    Thorongil ("Eagle of the Star"), Estel ("Hope")`,
        h44: ``,
        about: `Aragorn II, son of Arathorn II and Gilraen, also known as Elessar and Strider,
    was the 16th and last Chieftain of the Dúnedain of the North; later crowned
    King Elessar Telcontar (March 1, 2931 - FO 120), the 26th King of Arnor,
    35th King of Gondor and first High King of Gondor and Arnor since the short
    reign of Isildur. He was a great Ranger and warrior, and as Isildur's heir
    he bore the shards of Narsil,
    reforged and renamed Andúril, Flame of the West, in the War of the Ring.`,
        about1: ``,
        about2: ``,
    },

    {
        id: 2,
        race: 'human',
        person: 'Boromir',
        warPic: 'boromir',
        to1: `/Lotr1`,
        movie1: 'The Fellowship of the Ring (2001)',
        to2: ``,
        movie2: ``,
        to3: ``,
        movie3: ``,
        to4: ``,
        movie4: ``,
        to5: ``,
        movie5: ``,
        to6: ``,
        movie6: ``,
        to7: ``,
        movie7: ``,
        h4: `Captain of the White Tower, Captain-General,High Warden of the White Tower,`,
        h44: ``,
        about: `Boromir was a valiant warrior of Gondor, renowned for his
    prowess in combat and skill on the battlefield. He was the eldest son of Denethor II, who was Steward
    of Gondor during the War of the Ring, and his wife Finduilas. Even the people of Rohan admired him,
    particularly Éomer. He was the older brother of Faramir.`,
        about1: ``,
        about2: ``,
    },

    {
        id: 5,
        race: 'wizard',
        person: 'Gandalf',
        warPic: 'gandalf',
        to1: `/Lotr1`,
        movie1: 'The Fellowship of the Ring (2001)',
        to2: `/Lotr2`,
        movie2: 'The Two Towers (2002)',
        to3: `/Lotr3`,
        movie3: 'The Return of the King (2003)',
        to4: `/Hobbit1`,
        movie4: 'The Hobbit: An Unexpected Journey (2012)',
        to5: `/Hobbit2`,
        movie5: 'The Hobbit: The Desolation of Smaug (2013)',
        to6: `/Hobbit3`,
        movie6: `The Hobbit: The Battle of the Five Armies (2014)`,
        to7: ``,
        movie7: ``,
        h4: `Olórin, Mithrandir, Incánus, Tharkûn, Greyhame, Old Greybeard,
    The Grey Pilgrim, Stormcrow, White Rider, Láthspell, Gandalf the Wandering Wizard`,
        h44: ``,
        about: `Gandalf the Grey, later known as Gandalf the White, and
    originally named Olórin (Quenya; IPA: [oˈloːrin]), was an Istar (Wizard), dispatched to Middle-earth
    in the Third Age to combat the threat of Sauron. He joined Thorin II Oakenshield and his company to
    reclaim the Lonely Mountain from Smaug, helped form the Fellowship of the Ring to destroy the One Ring,
    and led the Free Peoples in the final campaign of the War of the Ring.`,
        about1: ``,
        about2: ``,
    },

    {
        id: 3,
        race: 'dwarf',
        person: 'Gimli',
        warPic: 'gimli',
        to1: `/Lotr1`,
        movie1: 'The Fellowship of the Ring (2001)',
        to2: `/Lotr2`,
        movie2: 'The Two Towers (2002)',
        to3: `/Lotr3`,
        movie3: 'The Return of the King (2003)',
        to4: ``,
        movie4: ``,
        to5: ``,
        movie5: ``,
        to6: ``,
        movie6: ``,
        to7: ``,
        movie7: ``,
        h4: `Elf-friend, Lockbearer`,
        h44: ``,
        about: `Gimli, son of Glóin, was a Dwarf of the House of Durin and a member of the Fellowship of the Ring. Unlike other Dwarves, he readily fought alongside Elves in the War of the Ring against Sauron at the end of the Third Age. After the defeat of Sauron, in the early Fourth Age, he was given the lordship over the Glittering Caves at Helm's Deep.`,
        about1: ``,
        about2: ``,
    },

    {
        id: 4,
        race: 'hobbit',
        person: 'Frodo Baggins',
        warPic: 'frodo',
        to1: `/Lotr1`,
        movie1: 'The Fellowship of the Ring (2001)',
        to2: `/Lotr2`,
        movie2: 'The Two Towers (2002)',
        to3: `/Lotr3`,
        movie3: 'The Return of the King (2003)',
        to4: ``,
        movie4: ``,
        to5: ``,
        movie5: ``,
        to6: ``,
        movie6: ``,
        to7: ``,
        movie7: ``,
        h4: `Frodo of the Nine Fingers, Nine-Fingered Frodo, Maura Labingi(Westron name), Mr. Underhill, Sneaky hobbit (by Gollum)`,
        h44: ``,
        about: `Frodo Baggins, son of Drogo Baggins, was a hobbit of the Shire in the late Third Age. He is commonly considered Tolkien's most renowned character for his leading role in the Quest of the Ring, in which he bore the One Ring to Mount Doom, where it was destroyed. He was a Ring-bearer, best friend to his gardener, Samwise Gamgee, and one of three hobbits who sailed from Middle-earth to the Uttermost West at the end of the Third Age.`,
        about1: ``,
        about2: ``,
    },

    {
        id: 6,
        race: 'hobbit',
        person: 'Samwise Gamgee',
        warPic: 'sam',
        to1: `/Lotr1`,
        movie1: 'The Fellowship of the Ring (2001)',
        to2: `/Lotr2`,
        movie2: 'The Two Towers (2002)',
        to3: `/Lotr3`,
        movie3: 'The Return of the King (2003)',
        to4: ``,
        movie4: ``,
        to5: ``,
        movie5: ``,
        to6: ``,
        movie6: ``,
        to7: ``,
        movie7: ``,
        h4: ``,
        h44: ``,
        about: `Samwise Gamgee, known as Sam, was a hobbit of the Shire. He was Frodo Baggins' gardener and best friend. Sam proved himself to be Frodo's closest and most dependable companion, the most loyal of the Fellowship of the Ring, and played a critical role in protecting Frodo and destroying the One Ring.`,
        about1: ``,
        about2: ``,
    },

    {
        id: 7,
        race: 'elf',
        person: 'Legolas',
        warPic: 'legolas',
        to1: `/Lotr1`,
        movie1: 'The Fellowship of the Ring (2001)',
        to2: `/Lotr2`,
        movie2: 'The Two Towers (2002)',
        to3: `/Lotr3`,
        movie3: 'The Return of the King (2003)',
        to4: ``,
        movie4: ``,
        to5: ``,
        movie5: ``,
        to6: ``,
        movie6: ``,
        to7: ``,
        movie7: ``,
        h4: 'Greenleaf',
        h44: ``,
        about: `Legolas was a Sindar Elf who was part of the Fellowship of the Ring in the Third Age. Son of the Elvenking Thranduil of Mirkwood, Legolas was Mirkwood's prince, a messenger, and a master archer. With his keen eyesight, sensitive hearing, and excellent bowmanship, Legolas was valuable to the Fellowship in their journey across Middle-earth. He was well-known for becoming friends with the Dwarf Gimli, despite their long-held differences.`,
        about1: ``,
        about2: ``,
    },

    {
        id: 8,
        race: 'hobbit',
        person: 'Merry Brandybuck',
        warPic: 'merry',
        to1: `/Lotr1`,
        movie1: 'The Fellowship of the Ring (2001)',
        to2: `/Lotr2`,
        movie2: 'The Two Towers (2002)',
        to3: `/Lotr3`,
        movie3: 'The Return of the King (2003)',
        to4: ``,
        movie4: ``,
        to5: ``,
        movie5: ``,
        to6: ``,
        movie6: ``,
        to7: ``,
        movie7: ``,
        h4: `Merry, "the Magnificent" Kalimac "Kali" Brandagamba Holdwine of the Shire`,
        h44: ``,
        about: 'Meriadoc "Merry" Brandybuck was a Hobbit of the Shire and one of Frodo Baggins cousins and closest friends. He loved boats and ponies and had a great interest in the maps of Middle-earth. He was also one of the nine companions of the Fellowship of the Ring, and later became the eighth Master of Buckland.',
        about1: ``,
        about2: ``,
    },

    {
        id: 9,
        race: 'hobbit',
        person: 'Peregrin Took',
        warPic: 'pippin',
        to1: `/Lotr1`,
        movie1: 'The Fellowship of the Ring (2001)',
        to2: `/Lotr2`,
        movie2: 'The Two Towers (2002)',
        to3: `/Lotr3`,
        movie3: 'The Return of the King (2003)',
        to4: ``,
        movie4: ``,
        to5: ``,
        movie5: ``,
        to6: ``,
        movie6: ``,
        to7: ``,
        movie7: ``,
        h4: `Pippin, Razanur Tûk, (Westron name) Ernil i Pheriannath, Thain Peregrin I, Fool of a Took`,
        h44: ``,
        about: `Peregrin Took, more commonly known as Pippin, was a hobbit of the Shire, and one of Frodo Baggins' youngest and closest friends. He was a member of the Fellowship of the Ring and, after the War of the Ring, became thirty-second Thain of the Shire.`,
        about1: ``,
        about2: ``,
    },


    {
        id: 10,
        race: 'hobbit',
        person: 'Smeagol',
        warPic: 'gollum',
        to1: `/Lotr1`,
        movie1: 'The Fellowship of the Ring (2001)',
        to2: `/Lotr2`,
        movie2: 'The Two Towers (2002)',
        to3: `/Lotr3`,
        movie3: 'The Return of the King (2003)',
        to4: ``,
        movie4: ``,
        to5: ``,
        movie5: ``,
        to6: ``,
        movie6: ``,
        to7: ``,
        movie7: ``,
        h4: `Trahald, Slinker, Stinker, Shelob's Sneak`,
        h44: ``,
        about: `Gollum, originally named Sméagol (or Trahald), was at first a Stoor, one of the three early Hobbit-types. The name Gollum was derived from the sound of his gurgling, choking cough.`,
        about1: `His life extended far beyond his nature, by the effects of possessing the One Ring. Sméagol was about 589 years old when he died, a remarkable age for a creature that was once a Hobbit, but he had been deformed and twisted in body and mind by the corruption of the Ring. His chief desire was to repossess the Ring that had enslaved him, and he pursued it for many years after Bilbo Baggins found it in Gollum's cave within the Misty Mountains. Inadvertently, Gollum would play a vital role in the ultimate Quest of the Ring.`,
        about2: ``,
    },

    {
        id: 11,
        race: 'hobbit',
        person: 'Bilbo Baggins',
        warPic: `bilbo`,
        to1: `/Lotr1`,
        movie1: 'The Fellowship of the Ring (2001)',
        to2: `/Lotr2`,
        movie2: '',
        to3: `/Lotr3`,
        movie3: 'The Return of the King (2003)',
        to4: `/Hobbit1`,
        movie4: 'The Hobbit: An Unexpected Journey (2012)',
        to5: `/Hobbit2`,
        movie5: 'The Hobbit: The Desolation of Smaug (2013)',
        to6: `/Hobbit3`,
        movie6: `The Hobbit: The Battle of the Five Armies (2014)`,
        to7: ``,
        movie7: ``,
        h4: `Elf-friend, Ring-bearer, Burglar, The Fly who Stings the Spider, Barrel Rider, etc.`,
        h44: ``,
        about: `Bilbo Baggins was a hobbit of the Shire, the main protagonist of The Hobbit and a secondary character in The Lord of the Rings.`,
        about1: `Gandalf suggested to Thorin and Company that they hire Bilbo Baggins to be their burglar in the Quest of Erebor, and later fought in the Battle of Five Armies. Bilbo was also one of the bearers of the One Ring, and the first to voluntarily give it up, although with some difficulty. He wrote many of his adventures in a book he called There and Back Again. Bilbo adopted his second-cousin-once-removed Frodo Baggins to be his heir after his parents, Drogo Baggins and Primula Brandybuck, drowned in the Brandywine River.`,
        about2: `Bilbo was the first hobbit to become famous in the world at large, and one of the few to set foot in the Undying Lands.`,
    },

    {
        id: 12,
        race: 'uruk-hai',
        person: `Lurtz`,
        warPic: `lurtz`,
        to1: `/Lotr1`,
        movie1: 'The Fellowship of the Ring (2001)',
        to2: ``,
        movie2: '',
        to3: ``,
        movie3: '',
        to4: ``,
        movie4: '',
        to5: ``,
        movie5: '',
        to6: ``,
        movie6: ``,
        to7: ``,
        movie7: ``,
        h4: ``,
        h44: ``,
        about: `Lurtz was the first leader of the Uruk-hai scouts created specifically for Peter Jackson's movie The Lord of the Rings: The Fellowship of the Ring. He was portrayed by New Zealand actor Lawrence Makoare.`,
        about1: `He is non-canonical as he was created for the films, and is not in the books.`,
        about2: ``,
    },

    {
        id: 13,
        race: 'elf',
        person: `Galadriel`,
        warPic: `galadriel`,
        to1: `/Lotr1`,
        movie1: 'The Fellowship of the Ring (2001)',
        to2: `/Lotr2`,
        movie2: 'The Two Towers (2002)',
        to3: `/Lotr3`,
        movie3: 'The Return of the King (2003)',
        to4: `/Hobbit1`,
        movie4: 'The Hobbit: An Unexpected Journey (2012)',
        to5: `/Hobbit2`,
        movie5: 'The Hobbit: The Desolation of Smaug (2013)',
        to6: `/Hobbit3`,
        movie6: `The Hobbit: The Battle of the Five Armies (2014)`,
        to7: ``,
        movie7: ``,
        h44: ``,
        h4: `Alatáriel, Artanis, Nerwen`,
        about: `Galadriel was the "Lady" of the woods of Lothlórien, which she ruled with Celeborn, her husband.`,
        about1: `One of the greatest of the Elves in Middle-earth, she surpassed nearly all others in beauty, knowledge, and power. She bore Nenya, one of the three Elven rings of power. J.R.R. Tolkien thought of her as one of the mightiest and fairest of all Elves remaining in Middle-earth in the Third Age.`,
        about2: `She was the only daughter and youngest child of Finarfin, prince of the Ñoldor, and Eärwen, whose cousin was Lúthien. Her elder brothers were Finrod Felagund, Orodreth, Angrod, and Aegnor. Galadriel was a niece of Fëanor, the most important Elf of the early First Age.`,
    },

    {
        id: 14,
        race: 'elf',
        warPic: `elrond`,
        to1: `/Lotr1`,
        movie1: 'The Fellowship of the Ring (2001)',
        to2: `/Lotr2`,
        movie2: 'The Two Towers (2002)',
        to3: `/Lotr3`,
        movie3: 'The Return of the King (2003)',
        to4: `/Hobbit1`,
        movie4: 'The Hobbit: An Unexpected Journey (2012)',
        to5: `/Hobbit2`,
        movie5: '',
        to6: `/Hobbit3`,
        movie6: `The Hobbit: The Battle of the Five Armies (2014)`,
        to7: ``,
        movie7: ``,
        h44: ``,
        person: 'Elrond',
        h4: `Lord of Rivendell; Bearer of Vilya; Vice-regent and herald to Gil-galad`,
        about: `Elrond (Sindarin: "Star-dome") Half-elf, Lord of Rivendell, was a mighty Elf-ruler of old who dwelt in Middle-earth from the First Age to the beginning of the Fourth Age. He was the father of Elladan and Elrohir and Arwen Undómiel, the eventual wife of Aragorn II Elessar.`,
        about1: ``,
        about2: ``,
    },

    {
        id: 15,
        race: 'elf',
        person: 'Arwen',
        warPic: `arwen`,
        to1: `/Lotr1`,
        movie1: 'The Fellowship of the Ring (2001)',
        to2: `/Lotr2`,
        movie2: 'The Two Towers (2002)',
        to3: `/Lotr3`,
        movie3: 'The Return of the King (2003)',
        to4: `/Hobbit1`,
        movie4: '',
        to5: `/Hobbit2`,
        movie5: '',
        to6: `/Hobbit3`,
        movie6: ``,
        to7: ``,
        movie7: ``,
        h44: ``,
        h4: `Arwen was the Half-elves daughter of Elrond and Celebrían. She was often called Arwen Undómiel or "Evenstar".`,
        about: `In marrying Aragorn II Elessar after the War of the Ring, she became Queen of the Reunited Kingdom of Arnor and Gondor, and like Beren and Lúthien before her, she united Elf and Man in peace, while becoming mortal.`,
        about1: ``,
        about2: ``,
    },

    {
        id: 16,
        race: 'dark-wizard',
        person: `Saruman`,
        warPic: `saruman`,
        to1: `/Lotr1`,
        movie1: 'The Fellowship of the Ring (2001)',
        to2: `/Lotr2`,
        movie2: 'The Two Towers (2002)',
        to3: `/Lotr3`,
        movie3: 'The Return of the King (2003)',
        to4: `/Hobbit1`,
        movie4: 'The Hobbit: An Unexpected Journey (2012)',
        to5: `/Hobbit2`,
        movie5: '',
        to6: `/Hobbit3`,
        movie6: `The Hobbit: The Battle of the Five Armies (2014)`,
        to7: ``,
        movie7: ``,
        h44: ``,
        h4: `Saruman the White, Saruman of Many Colours, The White Wizard, Saruman the Wise (by Gandalf), Sharkey, Curunir, Curumo, Tarindor`,
        about: `Saruman, also known as Saruman the White, was first of the order of Istari (Wizards), who came to Middle-earth as emissaries of the Valar in the Third Age. He was the Wizards' leader, and chief of the White Council that opposed Sauron. His extensive studies of dark magic, however, eventually led him to desire the One Ring and lust for power. Thinking he could gain it for himself or become Sauron's servant alone, Saruman allied Isengard with Mordor in the War of the Ring, in which he was defeated. He is one of the few characters in The Lord of the Rings who is morally "grey" - being neither a genuine servant of evil nor an agent of good. He ultimately trusts only his own counsel and schemes for his own ends.`,
        about1: ``,
        about2: ``,
    },

    {
        id: 17,
        race: 'dark-wizard',
        person: 'Sauron',
        warPic: `sauron`,
        to1: `/Lotr1`,
        movie1: 'The Fellowship of the Ring (2001)',
        to2: `/Lotr2`,
        movie2: 'The Two Towers (2002)',
        to3: `/Lotr3`,
        movie3: 'The Return of the King (2003)',
        to4: `/Hobbit1`,
        movie4: 'The Hobbit: An Unexpected Journey (2012)',
        to5: `/Hobbit2`,
        movie5: 'The Hobbit: The Desolation of Smaug (2013)',
        to6: `/Hobbit3`,
        movie6: `The Hobbit: The Battle of the Five Armies (2014)`,
        to7: ``,
        movie7: ``,
        h44: ``,
        h4: `Mairon, Annatar, Artano, Aulendil, Gorthaur, Zigûr`,
        about: `Sauron (Quenya; IPA [ˈsaʊron] or [ˈθaʊron]), the eponymous Lord of the Rings, was the greatest subversive Maia, the maker of the One Ring, renowned student of the Vala Aulë, and the most trusted lieutenant of Morgoth. After Morgoth's ousting by the Valar, Sauron became the second Dark Lord and sought to conquer Middle-earth and even Númenor through guileful trickery - the chief representation of which were the Rings of Power - or overwhelming legions.`,
        about1: `At the end of the Second Age, Sauron was defeated in the War of the Last Alliance of Elves and Men united under Gil-galad and Elendil. In the final battle, Isildur managed to cut the One Ring from him, dismantling Sauron's corporeal form and ridding him of much of his power. After centuries lying dormant, rebuilding strength and stirring awake evil things, Sauron returned to power late in the Third Age, but was permanently crippled in the War of the Ring after the destruction of his Ring in the fires of Mount Doom by Frodo Baggins and his spirit was claimed by the Void.`,
        about2: `To the Sindar of Beleriand, Sauron was known as Gorthaur in the First Age.`,
    },

    {
        id: 18,
        race: 'nazgul',
        person: 'Witch-king of Angmar',
        warPic: `witch`,
        to1: `/Lotr1`,
        movie1: 'The Fellowship of the Ring (2001)',
        to2: `/Lotr2`,
        movie2: 'The Two Towers (2002)',
        to3: `/Lotr3`,
        movie3: 'The Return of the King (2003)',
        to4: `/Hobbit1`,
        movie4: '',
        to5: `/Hobbit2`,
        movie5: '',
        to6: `/Hobbit3`,
        movie6: `The Hobbit: The Battle of the Five Armies (2014)`,
        to7: ``,
        movie7: ``,
        h44: ``,
        h4: `The Black Captain, Captain of Despair, Lord of Carrion, Dwimmerlaik, King of the Nine Riders, Morgul-lord`,
        about: `The Witch-king of Angmar, also known as the Lord of the Nazgûl, was the leader of the Nazgûl (Ringwraiths) and Sauron's second-in-command during the Second and Third Ages of Middle-earth.`,
        about1: `His precise identity is unknown, but he could be one of three noble lords of Númenor, who were corrupted by the Nine Rings of Power and thus became the undying Wraiths at the servitude of Sauron. After Sauron's defeat by the Last Alliance, the Witch-king eventually reappeared in the Third Age's 14th century to found the evil realm of Angmar, where he gained his infamous epithet and ruled for almost seven centuries until the three successor states of Arnor were finally conquered.`,
        about2: `The Witch-king returned to Mordor to facilitate Sauron's return to power, then took Gondor's city of Minas Ithil and refortified it as Minas Morgul, and snuffed out the line of Kings of Gondor. He led Sauron's armies in the War of the Ring, stabbed Frodo Baggins on Weathertop during the first months of Frodo's venture out of the Shire to Rivendell, and at the Battle of the Pelennor Fields he broke the Great Gate of Minas Tirith, killed King Théoden of Rohan, and met his own doom.`,
    },

    {
        id: 19,
        race: 'nazgul',
        person: `Nazgul`,
        warPic: `nazgul`,
        to1: `/Lotr1`,
        movie1: 'The Fellowship of the Ring (2001)',
        to2: `/Lotr2`,
        movie2: 'The Two Towers (2002)',
        to3: `/Lotr3`,
        movie3: 'The Return of the King (2003)',
        to4: `/Hobbit1`,
        movie4: '',
        to5: `/Hobbit2`,
        movie5: '',
        to6: `/Hobbit3`,
        movie6: `The Hobbit: The Battle of the Five Armies (2014)`,
        to7: ``,
        movie7: ``,
        h44: ``,
        h4: `Ringwraiths, Úlairi`,
        about: `The Nazgûl (Black Speech for "Ringwraiths") or Úlairi (Quenya), also known as the Black Riders or simply The Nine, were the dreaded ring-servants of the Dark Lord Sauron in Middle-earth throughout the Second and Third Ages, who in the later years of the Third Age dwelt in Minas Morgul and Dol Guldur.`,
        about1: ``,
        about2: ``,
    },

    {
        id: 20,
        race: 'uruk-hai',
        person: `Ugluk`,
        warPic: `ugluk`,
        to1: `/Lotr1`,
        movie1: '',
        to2: `/Lotr2`,
        movie2: 'The Two Towers (2002)',
        to3: `/Lotr3`,
        movie3: '',
        to4: `/Hobbit1`,
        movie4: '',
        to5: `/Hobbit2`,
        movie5: '',
        to6: `/Hobbit3`,
        movie6: ``,
        to7: ``,
        movie7: ``,
        h44: ``,
        h4: `Captain of the Uruk-hai`,
        about: `Uglúk was the leader of the Uruk-hai who were sent from Isengard to pursue the Fellowship of the Ring in TA 3019.`,
        about1: `Uglúk and his company ambushed the Fellowship of the Ring at Amon Hen, succeeding in capturing two of the company's four hobbits, Meriadoc Brandybuck and Peregrin Took. In the skirmish, Uglúk killed Boromir with arrows. Under orders from his lord Saruman, Uglúk's company set out towards Isengard.`,
        about2: `Uglúk stood by Saruman's demands when a band of Orcs from Moria, led by Grishnákh of Mordor, tried to apprehend Merry and Pippin to take them to Mordor. Uglúk beheaded one of Grishnákh's followers to prevent Saruman's orders from being disobeyed. The hobbits were taken some way further, but near the borders of Fangorn Forest, an Éored of Rohirrim led by Éomer attacked and wiped out the Uruk-hai. Uglúk was slain in single combat by Éomer himself during the fighting.`,
    },

    {
        id: 21,
        race: 'human',
        person: `Eowyn`,
        warPic: `eowyn`,
        to1: `/Lotr1`,
        movie1: '',
        to2: `/Lotr2`,
        movie2: 'The Two Towers (2002)',
        to3: `/Lotr3`,
        movie3: 'The Return of the King (2003)',
        to4: `/Hobbit1`,
        movie4: '',
        to5: `/Hobbit2`,
        movie5: '',
        to6: `/Hobbit3`,
        movie6: ``,
        to7: ``,
        movie7: ``,
        h44: ``,
        h4: `White Lady of Rohan, Shieldmaiden of Rohan, Lady of the Shield-arm, Lady of Ithilien, Lady of Emyn Arnen`,
        about: `Éowyn was a shieldmaiden of Rohan, daughter of Éomund and Théodwyn, younger sister of Éomer and niece of King Théoden. After the War of the Ring, she married Faramir and had one son with him, Elboron.`,
        about1: ``,
        about2: ``,
    },

    {
        id: 22,
        race: 'human',
        person: `Theoden`,
        warPic: `theoden`,
        to1: `/Lotr1`,
        movie1: '',
        to2: `/Lotr2`,
        movie2: 'The Two Towers (2002)',
        to3: `/Lotr3`,
        movie3: 'The Return of the King (2003)',
        to4: `/Hobbit1`,
        movie4: '',
        to5: `/Hobbit2`,
        movie5: '',
        to6: `/Hobbit3`,
        movie6: ``,
        to7: ``,
        movie7: ``,
        h44: ``,
        h4: `King of Rohan, Lord of the Mark, Horsemaster Father of Horse-men`,
        about: `Théoden, son of Thengel and Morwen Steelsheen, was the seventeenth King of Rohan, last of the Second Line of the royal House of Eorl.`,
        about1: ``,
        about2: ``,
    },

    {
        id: 23,
        race: 'human',
        person: `Eomer`,
        warPic: `eomer`,
        to1: `/Lotr1`,
        movie1: '',
        to2: `/Lotr2`,
        movie2: 'The Two Towers (2002)',
        to3: `/Lotr3`,
        movie3: 'The Return of the King (2003)',
        to4: `/Hobbit1`,
        movie4: '',
        to5: `/Hobbit2`,
        movie5: '',
        to6: `/Hobbit3`,
        movie6: ``,
        to7: ``,
        movie7: ``,
        h44: ``,
        h4: `Third Marshal of the Riddermark, Lord of the Mark, King of Rohan`,
        about: `Éomer Éadig was a Man of Rohan and the eventual eighteenth King of Rohan, and first of the Third Line of their Kings. In the last decade of the Third Age, Éomer was the Third Marshal of the Mark.`,
        about1: ``,
        about2: ``,
    },

    {
        id: 24,
        race: 'human',
        person: `Grima Wormtongue`,
        warPic: `grima`,
        to1: `/Lotr1`,
        movie1: '',
        to2: `/Lotr2`,
        movie2: 'The Two Towers (2002)',
        to3: `/Lotr3`,
        movie3: 'The Return of the King (2003)',
        to4: `/Hobbit1`,
        movie4: '',
        to5: `/Hobbit2`,
        movie5: '',
        to6: `/Hobbit3`,
        movie6: ``,
        to7: ``,
        movie7: ``,
        h44: ``,
        h4: `Worm, Snake, Wormtongue`,
        about: `Gríma Wormtongue was the chief counsellor at the court of King Théoden of Rohan before being exposed as an agent and mole of the corrupted wizard Saruman. Reduced to the level of a base thrall, he ends up as the slayer of his oppressive master in the last climactic chapter of The Return of the King.`,
        about1: ``,
        about2: ``,
    },

    {
        id: 25,
        race: 'human',
        person: `Faramir`,
        warPic: `faramir`,
        to1: `/Lotr1`,
        movie1: '',
        to2: `/Lotr2`,
        movie2: 'The Two Towers (2002)',
        to3: `/Lotr3`,
        movie3: 'The Return of the King (2003)',
        to4: `/Hobbit1`,
        movie4: '',
        to5: `/Hobbit2`,
        movie5: '',
        to6: `/Hobbit3`,
        movie6: ``,
        to7: ``,
        movie7: ``,
        h44: ``,
        h4: `Captain of the Rangers of Ithilien, Captain of the White Tower, Steward to the King of Gondor, Lord of Emyn Arnen, Prince of Ithilien`,
        about: `Faramir was the second son of Denethor II and the younger brother of Boromir. He was Captain of the Rangers of Ithilien and Captain of the White Tower upon his brother's death.`,
        about1: `After the War of the Ring, Faramir became the first Prince of Ithilien and married Éowyn of Rohan.`,
        about2: ``,
    },

    {
        id: 26,
        race: 'human',
        person: 'Denethor',
        warPic: `denethor`,
        to1: `/Lotr1`,
        movie1: '',
        to2: `/Lotr2`,
        movie2: '',
        to3: `/Lotr3`,
        movie3: 'The Return of the King (2003)',
        to4: `/Hobbit1`,
        movie4: '',
        to5: `/Hobbit2`,
        movie5: '',
        to6: `/Hobbit3`,
        movie6: ``,
        to7: ``,
        movie7: ``,
        h44: ``,
        h4: `Ruling Steward of Gondor, Lord of Gondor, Lord of Minas Tirith`,
        about: `Denethor II was the twenty-sixth and last Ruling Steward of Gondor, and father of War of the Ring heroes Boromir and Faramir.`,
        about1: ``,
        about2: ``,
    },

    {
        id: 27,
        race: 'wizard',
        person: 'King Of The Death',
        warPic: `kingofdeath`,
        to1: `/Lotr1`,
        movie1: '',
        to2: `/Lotr2`,
        movie2: '',
        to3: `/Lotr3`,
        movie3: 'The Return of the King (2003)',
        to4: `/Hobbit1`,
        movie4: '',
        to5: `/Hobbit2`,
        movie5: '',
        to6: `/Hobbit3`,
        movie6: ``,
        to7: ``,
        movie7: ``,
        h44: ``,
        h4: ``,
        about: `The King of the Dead, originally "King of the Mountains", was king of the Dead Men of the Mountains in Dwimorberg, and before that had been a living Man. His spirit resided along with that of his kin in the Paths of the Dead.`,
        about1: ``,
        about2: ``,
    },

    {
        id: 28,
        race: 'orc',
        person: 'Gothmog',
        warPic: `gothmog`,
        to1: `/Lotr1`,
        movie1: '',
        to2: `/Lotr2`,
        movie2: '',
        to3: `/Lotr3`,
        movie3: 'The Return of the King (2003)',
        to4: `/Hobbit1`,
        movie4: '',
        to5: `/Hobbit2`,
        movie5: '',
        to6: `/Hobbit3`,
        movie6: ``,
        to7: ``,
        movie7: ``,
        h44: ``,
        h4: `Lieutenant of Morgul`,
        about: `Gothmog was the lieutenant of the Witch-king in the Third Age from Minas Morgul, notably serving at the Battle of the Pelennor Fields.`,
        about1: ``,
        about2: ``,
    },

    {
        id: 29,
        race: 'orc',
        person: `Azog`,
        warPic: `azog`,
        to1: `/Lotr1`,
        movie1: '',
        to2: `/Lotr2`,
        movie2: '',
        to3: `/Lotr3`,
        movie3: '',
        to4: `/Hobbit1`,
        movie4: 'The Hobbit: An Unexpected Journey (2012)',
        to5: `/Hobbit2`,
        movie5: 'The Hobbit: The Desolation of Smaug (2013)',
        to6: `/Hobbit3`,
        movie6: `The Hobbit: The Battle of the Five Armies (2014)`,
        to7: ``,
        movie7: ``,
        h44: ``,
        h4: `Moria Orc`,
        about: `Azog was an Orc-lord of the Third Age who commanded the tribes of Moria until his death in TA 2799. He was responsible for the death of the Dwarven King Thrór.`,
        about1: ``,
        about2: ``,
    },

    {
        id: 30,
        race: 'dwarf',
        person: `Thorin Oakenshield`,
        warPic: `thorin`,
        to1: `/Lotr1`,
        movie1: '',
        to2: `/Lotr2`,
        movie2: '',
        to3: `/Lotr3`,
        movie3: '',
        to4: `/Hobbit1`,
        movie4: 'The Hobbit: An Unexpected Journey (2012)',
        to5: `/Hobbit2`,
        movie5: 'The Hobbit: The Desolation of Smaug (2013)',
        to6: `/Hobbit3`,
        movie6: `The Hobbit: The Battle of the Five Armies (2014)`,
        to7: ``,
        movie7: ``,
        h44: ``,
        h4: `King of Durin's Folk, King under the Mountain`,
        about: `Thorin II "Oakenshield", eventually called King under the Mountain or Mountain King, was the son of Thráin II, the older brother of Frerin and Dís, the grandson of King Thrór and the uncle of Fíli and Kíli. Thorin was best known for his deeds as leader of a company that infiltrated the lost Kingdom under the Mountain to take it back from Smaug and for leading an alliance of Men, Dwarves, and Elves in the Battle of Five Armies.`,
        about1: `"If more of us valued food and cheer and song above hoarded gold, it would be a merrier world. But, sad or merry, I must leave it now. Farewell." —The Hobbit, The Return Journey`,
        about2: ``,
    },

    {
        id: 31,
        race: 'dwarf',
        person: `Kili`,
        warPic: `kili`,
        to1: `/Lotr1`,
        movie1: '',
        to2: `/Lotr2`,
        movie2: '',
        to3: `/Lotr3`,
        movie3: '',
        to4: `/Hobbit1`,
        movie4: 'The Hobbit: An Unexpected Journey (2012)',
        to5: `/Hobbit2`,
        movie5: 'The Hobbit: The Desolation of Smaug (2013)',
        to6: `/Hobbit3`,
        movie6: `The Hobbit: The Battle of the Five Armies (2014)`,
        to7: ``,
        movie7: ``,
        h44: ``,
        h4: `Prince Kili, Brother (by Fili), Son of Dís`,
        about: `Kíli and his brother, Fíli were the third and fourth dwarves respectively to enter Bag End, and introduced the storyline. When Bilbo says they're at the wrong house, Kíli asked if the meeting has been canceled. Bilbo answers that nothing was canceled, and the brothers barge in as if invited in. Kíli gives Bilbo a hard time by rubbing his boots off of Bilbo's glorybox. He and his brother start the song "What Bilbo Baggins Hates" After Thorin enters, Kíli is optimistic when they realize there's another way in.`,
        about1: ``,
        about2: ``,
    },

    {
        id: 32,
        race: 'dwarf',
        person: `Fili`,
        warPic: `fili`,
        to1: `/Lotr1`,
        movie1: '',
        to2: `/Lotr2`,
        movie2: '',
        to3: `/Lotr3`,
        movie3: '',
        to4: `/Hobbit1`,
        movie4: 'The Hobbit: An Unexpected Journey (2012)',
        to5: `/Hobbit2`,
        movie5: 'The Hobbit: The Desolation of Smaug (2013)',
        to6: `/Hobbit3`,
        movie6: `The Hobbit: The Battle of the Five Armies (2014)`,
        to7: ``,
        movie7: ``,
        h44: ``,
        h4: `Prince Fili, Brother (by Kili), Son of Dís`,
        about: `Fíli (T.A. 2859 – 2941,[1] 82 years old) was one of the thirteen Dwarves who took part in the quest for Erebor, which was Bilbo Baggins's great adventure. He was one of the three Dwarves of Thorin's company who did not survive the Battle of Five Armies (the other two being his uncle Thorin and his brother Kíli.)`,
        about1: ``,
        about2: ``,
    },

    {
        id: 33,
        race: 'dwarf',
        person: `Ori`,
        warPic: `ori`,
        to1: `/Lotr1`,
        movie1: '',
        to2: `/Lotr2`,
        movie2: '',
        to3: `/Lotr3`,
        movie3: '',
        to4: `/Hobbit1`,
        movie4: 'The Hobbit: An Unexpected Journey (2012)',
        to5: `/Hobbit2`,
        movie5: 'The Hobbit: The Desolation of Smaug (2013)',
        to6: `/Hobbit3`,
        movie6: `The Hobbit: The Battle of the Five Armies (2014)`,
        to7: ``,
        movie7: ``,
        h44: ``,
        h4: `Ori the dwarf`,
        about: `Ori was a member of Thorin's Company of Dwarves and participated in the Quest of Erebor, as well as fighting in and surviving the Battle of Five Armies. He, along with his cousins Dori and Nori, were remote kinsmen of Thorin II Oakenshield.`,
        about1: ``,
        about2: ``,
    },

    {
        id: 34,
        race: 'dwarf',
        person: `Nori`,
        warPic: `nori`,
        to1: `/Lotr1`,
        movie1: '',
        to2: `/Lotr2`,
        movie2: '',
        to3: `/Lotr3`,
        movie3: '',
        to4: `/Hobbit1`,
        movie4: 'The Hobbit: An Unexpected Journey (2012)',
        to5: `/Hobbit2`,
        movie5: 'The Hobbit: The Desolation of Smaug (2013)',
        to6: `/Hobbit3`,
        movie6: `The Hobbit: The Battle of the Five Armies (2014)`,
        to7: ``,
        movie7: ``,
        h44: ``,
        h4: `Nori the dwarf`,
        about: `Nori was a Dwarf of Durin's Folk. He had a brother named Dori as well as a cousin named Ori, and was a remote kinsman of Thorin Oakenshield. His hood was purple, he played the flute, and he was very fond of regular and plentiful meals like his Hobbit friend, Bilbo Baggins.`,
        about1: ``,
        about2: ``,
    },

    {
        id: 35,
        race: 'dwarf',
        person: `Dori`,
        warPic: `dori`,
        to1: `/Lotr1`,
        movie1: '',
        to2: `/Lotr2`,
        movie2: '',
        to3: `/Lotr3`,
        movie3: '',
        to4: `/Hobbit1`,
        movie4: 'The Hobbit: An Unexpected Journey (2012)',
        to5: `/Hobbit2`,
        movie5: 'The Hobbit: The Desolation of Smaug (2013)',
        to6: `/Hobbit3`,
        movie6: `The Hobbit: The Battle of the Five Armies (2014)`,
        to7: ``,
        movie7: ``,
        h44: ``,
        h4: `Dori the dwarf`,
        about: `Dori was a Dwarf of Durin's Folk, who, along with his brother Nori and cousin Ori, travelled with Bilbo Baggins and Thorin Oakenshield as a member of Thorin's Company on theQuest for Erebor, to reclaim the Lonely Mountain from the dragon Smaug.`,
        about1: `Dori was among the Dwarves at Bag End who joined in singing about "blunting the knives" and "bending the forks"; as well as accompanying by playing the flute. He was described as “decent fellow despite his grumbling”. He often wore a red-violet coat while on the Quest for Erebor. He was noted by Thorin to be the strongest of the thirteen companions.`,
        about2: ``,
    },

    {
        id: 36,
        race: 'dwarf',
        person: `Bifur`,
        warPic: `bifur`,
        to1: `/Lotr1`,
        movie1: '',
        to2: `/Lotr2`,
        movie2: '',
        to3: `/Lotr3`,
        movie3: '',
        to4: `/Hobbit1`,
        movie4: 'The Hobbit: An Unexpected Journey (2012)',
        to5: `/Hobbit2`,
        movie5: 'The Hobbit: The Desolation of Smaug (2013)',
        to6: `/Hobbit3`,
        movie6: `The Hobbit: The Battle of the Five Armies (2014)`,
        to7: ``,
        movie7: ``,
        h44: ``,
        h4: `Bifur the dwarf`,
        about: `Bifur was a Dwarf of the late-Third Age. He is best known for being a companion to Bilbo Baggins and Thorin Oakenshield on the quest to regain the Lonely Mountain, along with his cousins Bofur and Bombur.`,
        about1: ``,
        about2: ``,
    },

    {
        id: 37,
        race: 'dwarf',
        person: `Bofur`,
        warPic: `bofur`,
        to1: `/Lotr1`,
        movie1: '',
        to2: `/Lotr2`,
        movie2: '',
        to3: `/Lotr3`,
        movie3: '',
        to4: `/Hobbit1`,
        movie4: 'The Hobbit: An Unexpected Journey (2012)',
        to5: `/Hobbit2`,
        movie5: 'The Hobbit: The Desolation of Smaug (2013)',
        to6: `/Hobbit3`,
        movie6: `The Hobbit: The Battle of the Five Armies (2014)`,
        to7: ``,
        movie7: ``,
        h44: ``,
        h4: `Bofur the dwarf`,
        about: `Bofur was a Dwarf of the late-Third Age. He is best known as a companion of Bilbo Baggins, Thorin Oakenshield, and Gandalf on the quest to reclaim the Lonely Mountain from the dragon Smaug, along with his brother Bombur and cousin Bifur.`,
        about1: ``,
        about2: ``,
    },

    {
        id: 38,
        race: 'dwarf',
        person: `Bombur`,
        warPic: `bombur`,
        to1: `/Lotr1`,
        movie1: '',
        to2: `/Lotr2`,
        movie2: '',
        to3: `/Lotr3`,
        movie3: '',
        to4: `/Hobbit1`,
        movie4: 'The Hobbit: An Unexpected Journey (2012)',
        to5: `/Hobbit2`,
        movie5: 'The Hobbit: The Desolation of Smaug (2013)',
        to6: `/Hobbit3`,
        movie6: `The Hobbit: The Battle of the Five Armies (2014)`,
        to7: ``,
        movie7: ``,
        h44: ``,
        h4: `Bombur the dwarf`,
        about: `Bombur was a Dwarf who accompanied Thorin Oakenshield and Bilbo Baggins on their quest to the Lonely Mountain as part of the company, alongside his brother Bofur and cousin Bifur. Bombur was noted as the fattest Dwarf in the company.`,
        about1: ``,
        about2: ``,
    },

    {
        id: 39,
        race: 'dwarf',
        person: `Gloin`,
        warPic: `gloin`,
        to1: `/Lotr1`,
        movie1: '',
        to2: `/Lotr2`,
        movie2: '',
        to3: `/Lotr3`,
        movie3: '',
        to4: `/Hobbit1`,
        movie4: 'The Hobbit: An Unexpected Journey (2012)',
        to5: `/Hobbit2`,
        movie5: 'The Hobbit: The Desolation of Smaug (2013)',
        to6: `/Hobbit3`,
        movie6: `The Hobbit: The Battle of the Five Armies (2014)`,
        to7: ``,
        movie7: ``,
        h44: ``,
        h4: `Gloin the dwarf`,
        about: `Glóin, son of Gróin was one of the Dwarves of Thorin II Oakenshield's company who set out to reclaim the Lonely Mountain in the Quest of Erebor. He was also the father of Gimli, who became a member of the Fellowship of the Ring.`,
        about1: `Glóin chiefly appears in The Hobbit as a supporting character. Glóin also appears in The Fellowship of the Ring during the Council of Elrond.`,
        about2: ``,
    },

    {
        id: 40,
        race: 'dwarf',
        person: `Oin`,
        warPic: `oin`,
        to1: `/Lotr1`,
        movie1: '',
        to2: `/Lotr2`,
        movie2: '',
        to3: `/Lotr3`,
        movie3: '',
        to4: `/Hobbit1`,
        movie4: 'The Hobbit: An Unexpected Journey (2012)',
        to5: `/Hobbit2`,
        movie5: 'The Hobbit: The Desolation of Smaug (2013)',
        to6: `/Hobbit3`,
        movie6: `The Hobbit: The Battle of the Five Armies (2014)`,
        to7: ``,
        movie7: ``,
        h44: ``,
        h4: `Oin the dwarf`,
        about: `Óin (T.A. 2774 - 2994, 220 years old) was one of the Dwarves of Thorin's company who set out to reclaim Erebor from Smaug. Later, he followed Balin in an ill-fated attempt to retake Moria.`,
        about1: ``,
        about2: ``,
    },

    {
        id: 41,
        race: 'dwarf',
        person: `Balin`,
        warPic: `balin`,
        to1: `/Lotr1`,
        movie1: '',
        to2: `/Lotr2`,
        movie2: '',
        to3: `/Lotr3`,
        movie3: '',
        to4: `/Hobbit1`,
        movie4: 'The Hobbit: An Unexpected Journey (2012)',
        to5: `/Hobbit2`,
        movie5: 'The Hobbit: The Desolation of Smaug (2013)',
        to6: `/Hobbit3`,
        movie6: `The Hobbit: The Battle of the Five Armies (2014)`,
        to7: ``,
        movie7: ``,
        h44: ``,
        h4: `Lord of Moria`,
        about: `Balin was a Dwarf leader, the son of Fundin, and elder brother of Dwalin. He was one of the thirteen Dwarves who accompanied Thorin II Oakenshield on the quest to regain the Lonely Mountain.`,
        about1: `A Dwarf Lord known for his wise counsel and willingness to listen, he was one of Thorin's closest friends and advisers. Balin was distantly related to him, and a descendant of the noble House of Durin.`,
        about2: `He later went to re-establish the Dwarf presence in Moria, but within five years it was overcome once more by Orcs, and he was killed there along with the rest of his companions.`,
    },

    {
        id: 42,
        race: 'dwarf',
        person: `Dwalin`,
        warPic: `dwalin`,
        to1: `/Lotr1`,
        movie1: '',
        to2: `/Lotr2`,
        movie2: '',
        to3: `/Lotr3`,
        movie3: '',
        to4: `/Hobbit1`,
        movie4: 'The Hobbit: An Unexpected Journey (2012)',
        to5: `/Hobbit2`,
        movie5: 'The Hobbit: The Desolation of Smaug (2013)',
        to6: `/Hobbit3`,
        movie6: `The Hobbit: The Battle of the Five Armies (2014)`,
        to7: ``,
        movie7: ``,
        h44: ``,
        h4: `Blue beard`,
        about: `Dwalin was one of the Dwarves who traveled with Bilbo and Gandalf as a member of Thorin and Company on the quest to regain the Lonely Mountain from the Dragon Smaug. He was the brother of Balin and the youngest son of Fundin.`,
        about1: ``,
        about2: ``,
    },

    {
        id: 43,
        race: 'wizard',
        person: `Radagast`,
        warPic: `radagast`,
        to1: `/Lotr1`,
        movie1: '',
        to2: `/Lotr2`,
        movie2: '',
        to3: `/Lotr3`,
        movie3: '',
        to4: `/Hobbit1`,
        movie4: 'The Hobbit: An Unexpected Journey (2012)',
        to5: `/Hobbit2`,
        movie5: 'The Hobbit: The Desolation of Smaug (2013)',
        to6: `/Hobbit3`,
        movie6: `The Hobbit: The Battle of the Five Armies (2014)`,
        to7: ``,
        movie7: ``,
        h44: `Aiwendil, Hrávandil, Tender of Beasts, Bird Friend, "the Bird-tamer", "the Simple", "the Fool"`,
        h4: `The Brown Wizard`,
        about: `Radagast (Adûnaic; IPA: ['radagast] - "Tender Of Beasts") the Brown was one of five Wizards sent to Middle-earth to contest the will of Sauron. Originally a Maia of Yavanna, Radagast mainly concerned himself with the well-being of the plant and animal worlds, and thus did not participate heavily in the War of the Ring.`,
        about1: ``,
        about2: ``,
    },

    {
        id: 44,
        race: 'goblin',
        person: `Great Goblin`,
        warPic: `greatgoblin`,
        to1: `/Lotr1`,
        movie1: '',
        to2: `/Lotr2`,
        movie2: '',
        to3: `/Lotr3`,
        movie3: '',
        to4: `/Hobbit1`,
        movie4: 'The Hobbit: An Unexpected Journey (2012)',
        to5: `/Hobbit2`,
        movie5: '',
        to6: `/Hobbit3`,
        movie6: ``,
        to7: ``,
        movie7: ``,
        h44: ``,
        h4: `Chieftain of Goblin-town`,
        about: `The Great Goblin was a large goblin chieftain of the Misty Mountains in Middle-earth during the Third Age.`,
        about1: ``,
        about2: ``,
    },

    {
        id: 45,
        race: 'troll',
        person: `Tom`,
        warPic: `tom`,
        to1: `/Lotr1`,
        movie1: '',
        to2: `/Lotr2`,
        movie2: '',
        to3: `/Lotr3`,
        movie3: '',
        to4: `/Hobbit1`,
        movie4: 'The Hobbit: An Unexpected Journey (2012)',
        to5: `/Hobbit2`,
        movie5: '',
        to6: `/Hobbit3`,
        movie6: ``,
        to7: ``,
        movie7: ``,
        h44: ``,
        h4: `Stone Troll`,
        about: `Tom, Bert, and William ("Bill") Huggins were three Stone-trolls that Bilbo Baggins encountered in the Trollshaws, in Eriador, while with Thorin and Company on their quest to regain the Lonely Mountain (Erebor). Like most of their kind outside of Mordor, they were vagabonds who robbed, stole, and killed for what they needed or wanted. Their age is unknown. They were destroyed by sunlight which turned them to stone with the aid of Gandalf's trickery.`,
        about1: ``,
        about2: ``,
    },

    {
        id: 46,
        race: 'troll',
        person: `Bert`,
        warPic: `bert`,
        to1: `/Lotr1`,
        movie1: '',
        to2: `/Lotr2`,
        movie2: '',
        to3: `/Lotr3`,
        movie3: '',
        to4: `/Hobbit1`,
        movie4: 'The Hobbit: An Unexpected Journey (2012)',
        to5: `/Hobbit2`,
        movie5: '',
        to6: `/Hobbit3`,
        movie6: ``,
        to7: ``,
        movie7: ``,
        h44: ``,
        h4: `Stone Troll`,
        about: `Tom, Bert, and William ("Bill") Huggins were three Stone-trolls that Bilbo Baggins encountered in the Trollshaws, in Eriador, while with Thorin and Company on their quest to regain the Lonely Mountain (Erebor). Like most of their kind outside of Mordor, they were vagabonds who robbed, stole, and killed for what they needed or wanted. Their age is unknown. They were destroyed by sunlight which turned them to stone with the aid of Gandalf's trickery.`,
        about1: ``,
        about2: ``,
    },


    {
        id: 47,
        race: 'troll',
        person: `William`,
        warPic: `william`,
        to1: `/Lotr1`,
        movie1: '',
        to2: `/Lotr2`,
        movie2: '',
        to3: `/Lotr3`,
        movie3: '',
        to4: `/Hobbit1`,
        movie4: 'The Hobbit: An Unexpected Journey (2012)',
        to5: `/Hobbit2`,
        movie5: '',
        to6: `/Hobbit3`,
        movie6: ``,
        to7: ``,
        movie7: ``,
        h44: ``,
        h4: `Stone Troll`,
        about: `Tom, Bert, and William ("Bill") Huggins were three Stone-trolls that Bilbo Baggins encountered in the Trollshaws, in Eriador, while with Thorin and Company on their quest to regain the Lonely Mountain (Erebor). Like most of their kind outside of Mordor, they were vagabonds who robbed, stole, and killed for what they needed or wanted. Their age is unknown. They were destroyed by sunlight which turned them to stone with the aid of Gandalf's trickery.`,
        about1: ``,
        about2: ``,
    },

    {
        id: 48,
        race: 'human',
        person: `Bard`,
        warPic: `bard`,
        to1: `/Lotr1`,
        movie1: '',
        to2: `/Lotr2`,
        movie2: '',
        to3: `/Lotr3`,
        movie3: '',
        to4: `/Hobbit1`,
        movie4: '',
        to5: `/Hobbit2`,
        movie5: 'The Hobbit: The Desolation of Smaug (2013)',
        to6: `/Hobbit3`,
        movie6: `The Hobbit: The Battle of the Five Armies (2014)`,
        to7: ``,
        movie7: ``,
        h44: `Bard the Dragonslayer`,
        h4: `Bard the Bowman`,
        about: `Bard, known also as Bard the Bowman, and also Bard I, was a Man of Lake-town, the slayer of the dragon Smaug, and the founder and first king of the new Kingdom of Dale. He was succeeded as King of Dale by his son, Bain.`,
        about1: ``,
        about2: ``,
    },

    {
        id: 49,
        race: 'skin-changer',
        person: `Beorn`,
        warPic: `beorn`,
        to1: `/Lotr1`,
        movie1: '',
        to2: `/Lotr2`,
        movie2: '',
        to3: `/Lotr3`,
        movie3: '',
        to4: `/Hobbit1`,
        movie4: '',
        to5: `/Hobbit2`,
        movie5: 'The Hobbit: The Desolation of Smaug (2013)',
        to6: `/Hobbit3`,
        movie6: `The Hobbit: The Battle of the Five Armies (2014)`,
        to7: ``,
        movie7: ``,
        h44: ``,
        h4: `Chieftain of the Beornings`,
        about: `Beorn was a Northman, skin-changer, and a Beorning chieftain who lived near the River Anduin between Mirkwood and the Misty Mountains. His kin lived in that region during the last centuries of the Third Age, guarding the Ford of Carrock from the Goblins and Wargs.[1] He was the father of Grimbeorn the Old.`,
        about1: `"If you must know more, his name is Beorn. He is very strong, and he is a skin-changer." —Gandalf the Grey`,
        about2: ``,
    },

    {
        id: 50,
        race: 'human',
        person: `Master of Lake-town`,
        warPic: `master`,
        to1: `/Lotr1`,
        movie1: '',
        to2: `/Lotr2`,
        movie2: '',
        to3: `/Lotr3`,
        movie3: '',
        to4: `/Hobbit1`,
        movie4: '',
        to5: `/Hobbit2`,
        movie5: 'The Hobbit: The Desolation of Smaug (2013)',
        to6: `/Hobbit3`,
        movie6: `The Hobbit: The Battle of the Five Armies (2014)`,
        to7: ``,
        movie7: ``,
        h44: ``,
        h4: `The Master, Moneybag`,
        about: `The Master of Lake-town or "The Master" was the original leader of Lake-town when Bilbo Baggins and his companions arrived. He is described as being greedy, but not undeserving of his position in terms of intelligence and charisma. He was an acquaintance of Bard the Bowman, and the captain of the town archers, allowing him to remain in Lake-town while the Lake-men recovered from their ordeal with Smaug.`,
        about1: `His actual name is unknown.`,
        about2: ``,
    },

    {
        id: 51,
        race: 'orc',
        person: `Bolg`,
        warPic: `bolg`,
        to1: `/Lotr1`,
        movie1: '',
        to2: `/Lotr2`,
        movie2: '',
        to3: `/Lotr3`,
        movie3: '',
        to4: `/Hobbit1`,
        movie4: '',
        to5: `/Hobbit2`,
        movie5: 'The Hobbit: The Desolation of Smaug (2013)',
        to6: `/Hobbit3`,
        movie6: `The Hobbit: The Battle of the Five Armies (2014)`,
        to7: ``,
        movie7: ``,
        h44: ``,
        h4: `Bolg of the North`,
        about: `Bolg was an Orc leader of the Misty Mountains in the late Third Age, and the son of Azog.`,
        about1: ``,
        about2: ``,
    },

    {
        id: 51,
        race: 'dragon',
        person: `Smaug`,
        warPic: `smaug`,
        to1: `/Lotr1`,
        movie1: '',
        to2: `/Lotr2`,
        movie2: '',
        to3: `/Lotr3`,
        movie3: '',
        to4: `/Hobbit1`,
        movie4: '',
        to5: `/Hobbit2`,
        movie5: 'The Hobbit: The Desolation of Smaug (2013)',
        to6: `/Hobbit3`,
        movie6: `The Hobbit: The Battle of the Five Armies (2014)`,
        to7: ``,
        movie7: ``,
        h44: `King under the Mountain`,
        h4: `Smaug the Golden, Smaug the Impenetrable, Smaug the Terrible, The Dragon Dread; Trāgu`,
        about: `"My armour is like tenfold shields, my teeth are swords, my claws spears, the shock of my tail is a thunderbolt, my wings a hurricane, and my breath death!"
            —The Hobbit, "Inside Information"`,
        about1: `Smaug was a fire-drake of the Third Age, considered to be the last "great" dragon of Middle-earth. He was drawn to the enormous wealth amassed by the Dwarves of the Lonely Mountain during King Thrór's reign. He laid waste to the nearby city of Dale and captured the Lonely Mountain, driving the surviving Dwarves into exile.`,
        about2: `For 171 years, Smaug hoarded the Lonely Mountain's treasures to himself, staying within the mountain, until a company of Dwarves managed to enter the Lonely Mountain and awaken him from hibernation. Correctly believing that the Dwarves had received assistance from the men of Lake-town in entering the Lonely Mountain, Smaug left the mountain to wreak destruction upon Lake-town, nearly destroying it before being slain by Bard the Bowman.`,
    },

    {
        id: 52,
        race: 'orc',
        to1: `/warcraft`,
        movie1: `Warcraft, The Beginning`,
        to2: ``,
        movie2: ``,
        to3: ``,
        movie3: ``,
        to4: ``,
        movie4: ``,
        to5: ``,
        movie5: ``,
        to6: ``,
        movie6: ``,
        to7: ``,
        movie7: ``,
        warPic: 'durotan',
        person: 'Durotan',
        h4: `Chieftain of the Frostwolf clan`,
        h44: ``,
        about: `Durotan, son of Garad and Geyah, was the chieftain of the Frostwolf clan, mate of Draka and father of the future Warchief Thrall. He was also a contemporary of Orgrim Doomhammer.`,
        about1: ``,
        about2: ``,
    },

    {
        id: 53,
        race: 'orc',
        to1: `/warcraft`,
        movie1: `Warcraft, The Beginning`,
        to2: ``,
        movie2: ``,
        to3: ``,
        movie3: ``,
        to4: ``,
        movie4: ``,
        to5: ``,
        movie5: ``,
        to6: ``,
        movie6: ``,
        to7: ``,
        movie7: ``,
        warPic: 'orgrim',
        person: `Orgrim Doomhammer`,
        h4: `Warchief of the Horde, Blackrock Chieftain, Backstabber, The Doomhammer`,
        h44: ``,
        about: `Orgrim Doomhammer was the Warchief of the Old Horde and Chieftain of the Blackrock clan during the end of the First War and the entirety of the Second War. The orcish capital of Orgrimmar, the Horde-controlled town of Hammerfall in the Arathi Highlands, and the flying battleship Orgrim's Hammer patrolling the skies of Icecrown, are named in his honor. He was also known as the Backstabber by loyalists of Gul'dan and Blackhand.`,
        about1: ``,
        about2: ``,
    },

    {
        id: 54,
        race: 'elf',
        person: `Tauriel`,
        warPic: `tauriel`,
        to1: `/Lotr1`,
        movie1: '',
        to2: `/Lotr2`,
        movie2: '',
        to3: `/Lotr3`,
        movie3: '',
        to4: `/Hobbit1`,
        movie4: '',
        to5: `/Hobbit2`,
        movie5: 'The Hobbit: The Desolation of Smaug (2013)',
        to6: `/Hobbit3`,
        movie6: `The Hobbit: The Battle of the Five Armies (2014)`,
        to7: ``,
        movie7: ``,
        h44: ``,
        h4: `Wood-elf of Mirkwood`,
        about: `Tauriel was a Wood-elf of Mirkwood, and captain of the Elven guard of Thranduil's Woodland Realm. Tauriel is a non-canonical character; invented not by J.R.R. Tolkien, but for Peter Jackson's The Hobbit film trilogy.`,
        about1: ``,
        about2: ``,
    },

    {
        id: 55,
        race: 'wizard',
        person: `Khadgar`,
        warPic: `khadgar`,
        to1: `/Lotr1`,
        movie1: '',
        to2: `/Lotr2`,
        movie2: '',
        to3: `/Lotr3`,
        movie3: '',
        to4: `/Hobbit1`,
        movie4: '',
        to5: `/Hobbit2`,
        movie5: '',
        to6: `/Hobbit3`,
        movie6: ``,
        to7: `/warcraft`,
        movie7: `Warcraft, The Beginning`,
        h44: ``,
        h4: `The Seeker, Guardian Novitiate, The Prodigy`,
        about: `Khadgar is a young mage of 17 or 18, and ex-student of the Kirin Tor. Following his aid to the forces of Stormwind during the invasion of the orcs, Khadgar appears to be a trusted advisor to the throne, and the burgeoning Alliance.`,
        about1: `Although no longer a member of the Kirin Tor, the teenager has proven himself to be a formidable mage, stronger in some ways even than the former Guardian Medivh. Indeed, Khadgar could have been Guardian had things been different.`,
        about2: ``,
    },

    {
        id: 56,
        race: 'wizard',
        person: `Medivh`,
        warPic: `medivh`,
        to1: `/Lotr1`,
        movie1: '',
        to2: `/Lotr2`,
        movie2: '',
        to3: `/Lotr3`,
        movie3: '',
        to4: `/Hobbit1`,
        movie4: '',
        to5: `/Hobbit2`,
        movie5: '',
        to6: `/Hobbit3`,
        movie6: ``,
        to7: `/warcraft`,
        movie7: `Warcraft, The Beginning`,
        h44: ``,
        h4: `The Guardian`,
        about: `“The fel... it's twisted me, I... I don't even know what else I may have done. I just don't remember. Everything I've thought to protect, I have destroyed.”

        — Medivh`,
        about1: `Medivh was a Guardian of Azeroth, and childhood friend of Llane Wrynn and Anduin Lothar, until his corruption by the fel turned him against them. After unwittingly opening the Great Gate and inviting the Horde to Azeroth, Medivh was fought by Khadgar and Lothar, and eventually killed.`,
        about2: `Despite his actions while possessed, Medivh remained a defender of Azeroth, and before dying was able to briefly assist the army of Stormwind in their assault on the orc encampment. Khadgar would later discover that it was the burden of isolation imposed on Medivh by his role as Guardian that made him vulnerable to the fel's corruption, his loneliness ultimately leading to his downfall.`,
    },

    {
        id: 57,
        race: 'dark-wizard',
        person: `Guldan`,
        warPic: `guldan`,
        to1: `/Lotr1`,
        movie1: '',
        to2: `/Lotr2`,
        movie2: '',
        to3: `/Lotr3`,
        movie3: '',
        to4: `/Hobbit1`,
        movie4: '',
        to5: `/Hobbit2`,
        movie5: '',
        to6: `/Hobbit3`,
        movie6: ``,
        to7: `/warcraft`,
        movie7: `Warcraft, The Beginning`,
        h44: `The Invader`,
        h4: `Chieftain of the Horde`,
        about: `Gul'dan is the founder and true leader of the orcish Horde. The first orc warlock, Gul'dan uses the power of the fel to drain the life from his enemies, and to corrupt and twist his warriors into even more terrifying forms.`,
        about1: `After his fel magic sickened the orcs' homeworld of Draenor, Gul'dan created the Horde to lead them to a plunder the world of Azeroth. Colluding with a demonic being, Gul'dan channeled the life energy of countless draenei to open the Great Gate, tearing a gateway between the two worlds, and led a warband through to conquer the new world.`,
        about2: `Although Gul'dan's plans to bring the rest of his Horde through to Azeroth have been thwarted for now, and his hold over the orcs is less certain than before, he remains in command of the orcish forces, as well as his own formidable powers, and is perhaps the greatest single enemy of the Alliance.`,
    },

    {
        id: 58,
        race: 'orc',
        person: `Blackhand`,
        warPic: `blackhand`,
        to1: `/Lotr1`,
        movie1: '',
        to2: `/Lotr2`,
        movie2: '',
        to3: `/Lotr3`,
        movie3: '',
        to4: `/Hobbit1`,
        movie4: '',
        to5: `/Hobbit2`,
        movie5: '',
        to6: `/Hobbit3`,
        movie6: ``,
        to7: `/warcraft`,
        movie7: `Warcraft, The Beginning`,
        h44: `Warchief of the Horde`,
        h4: `The Destroyer`,
        about: `Blackhand was the Warchief of the Horde, and the mightiest warrior the Horde had ever known. Although a ruthless war leader, he still held respect for tradition, placing honor above victory or even his own survival.`,
        about1: `After passing through the Great Gate, Blackhand led the orcish warband on their raids of the denizens of the Eastern Kingdoms. Following the battle at the Great Gate, he challenged Anduin Lothar to mak'gora, where he was defeated by the human warrior.`,
        about2: ``,
    },

    {
        id: 59,
        race: 'orc',
        person: `Darkscare`,
        warPic: `darkscare`,
        to1: `/Lotr1`,
        movie1: '',
        to2: `/Lotr2`,
        movie2: '',
        to3: `/Lotr3`,
        movie3: '',
        to4: `/Hobbit1`,
        movie4: '',
        to5: `/Hobbit2`,
        movie5: '',
        to6: `/Hobbit3`,
        movie6: ``,
        to7: `/warcraft`,
        movie7: `Warcraft, The Beginning`,
        h44: `Orc Warrior`,
        h4: ``,
        about: ``,
        about1: ``,
        about2: ``,
    },

    {
        id: 60,
        race: 'dwarf',
        person: `Muradin Bronzebeard`,
        warPic: `muradin`,
        to1: `/Lotr1`,
        movie1: '',
        to2: `/Lotr2`,
        movie2: '',
        to3: `/Lotr3`,
        movie3: '',
        to4: `/Hobbit1`,
        movie4: '',
        to5: `/Hobbit2`,
        movie5: '',
        to6: `/Hobbit3`,
        movie6: ``,
        to7: `/warcraft`,
        movie7: `Warcraft, The Beginning`,
        h44: `Prince of Khaz Modan`,
        h4: `Bronzebeard dwarf`,
        about: `Muradin Bronzebeard is a hero of the Alliance, the younger brother of the dwarven King Magni Bronzebeard and the older brother of the renowned explorer Brann Bronzebeard. Muradin was believed to have perished in Northrend when the young prince Arthas Menethil claimed the runeblade Frostmourne. However, recent events have indicated Muradin survived this brush with death, and wandered the wastes of Northrend with no memory of the incident until a chance encounter several years later.`,
        about1: ``,
        about2: ``,
    },

    {
        id: 61,
        race: 'dwarf',
        person: `Magni Bronzebeard`,
        warPic: `magni`,
        to1: `/Lotr1`,
        movie1: '',
        to2: `/Lotr2`,
        movie2: '',
        to3: `/Lotr3`,
        movie3: '',
        to4: `/Hobbit1`,
        movie4: '',
        to5: `/Hobbit2`,
        movie5: '',
        to6: `/Hobbit3`,
        movie6: ``,
        to7: `/warcraft`,
        movie7: `Warcraft, The Beginning`,
        h44: `Lord of Ironforge`,
        h4: `King of Khaz Modan, King under the Mountain, Grand Explorer, The Speaker`,
        about: `Magni Bronzebeard was the King of the dwarven kingdom of Khaz Modan, head of the Bronzebeard Clan, and head of the Senate of Ironforge.[citation needed] During the Second War he defended Ironforge from the orcs and joined the Alliance. He was a founding member of the Explorers' League, led by his brother Brann, and forged the Ashbringer hoping it would avenge his brother Muradin, who was believed to have been killed by the Scourge. Magni passed leadership of the dwarven people to the Council of Three Hammers, acting on the warnings of Azeroth to become her servant and warn the Alliance and Horde about the impending invasion of the Burning Legion`,
        about1: `With the Burning Legion and Sargeras defeated, Magni turned his attention to the wound suffered at Sargeras' hand, the massive sword plunged into Silithus. Knowing azerite was the lifeblood of Azeroth, he sought out adventurers to stem the flow. Once accomplished, he tried to dissuade the factions from fighting against one another.`,
        about2: ``,
    },

    {
        id: 62,
        race: 'orc',
        person: `Garona Halforcen`,
        warPic: `garona`,
        to1: `/Lotr1`,
        movie1: '',
        to2: `/Lotr2`,
        movie2: '',
        to3: `/Lotr3`,
        movie3: '',
        to4: `/Hobbit1`,
        movie4: '',
        to5: `/Hobbit2`,
        movie5: '',
        to6: `/Hobbit3`,
        movie6: ``,
        to7: `/warcraft`,
        movie7: `Warcraft, The Beginning`,
        h44: `Shadow, Emissary`,
        h4: ``,
        about: `Garona Halforcen is a half-orc half-draenei, though most (including herself) believed she was half-human until the truth was revealed to her. She is an assassin and was an emissary of the Horde during the first invasion of Azeroth, and was the reluctant murderer of King Llane Wrynn. Later on, she joined her son and the other members of the New Council of Tirisfal in their battle against the Twilight's Hammer cult.`,
        about1: `Recently, Garona has been aiding the Horde, notably during the war against Deathwing and the Fourth War. She is also one of the leaders of the Uncrowned.`,
        about2: ``,
    },

    {
        id: 63,
        race: 'human',
        person: `Anduin Lothar`,
        warPic: `anduin`,
        to1: `/Lotr1`,
        movie1: '',
        to2: `/Lotr2`,
        movie2: '',
        to3: `/Lotr3`,
        movie3: '',
        to4: `/Hobbit1`,
        movie4: '',
        to5: `/Hobbit2`,
        movie5: '',
        to6: `/Hobbit3`,
        movie6: ``,
        to7: `/warcraft`,
        movie7: `Warcraft, The Beginning`,
        h44: `Supreme Commander of the Alliance`,
        h4: `Supreme Allied Commander, Lion of Azeroth, Regent Lord of Stormwind, Knight Champion of Azeroth, Champion of Stormwind, Knight of the Realm, King's Champion, Lord, Commander, Sir`,
        about: `Sir Anduin Lothar, the Lion of Stormwind, was the last true descendant of the ancient Arathi bloodline, a Knight Champion of the Kingdom of Stormwind during the First War, and the Supreme Commander of the armies of the Alliance of Lordaeron during the Second War. He perished in combat at the base of Blackrock Mountain just before the end of the Second War and the closing of the Dark Portal. He is considered one of the greatest warriors in human history. King Varian Wrynn named his son, the current King of Stormwind, after him.`,
        about1: `He was one of the main protagonists in Orcs & Humans and Tides of Darkness.`,
        about2: ``,
    },

    {
        id: 64,
        race: 'human',
        person: `Llane Wrynn I`,
        warPic: `llane`,
        to1: `/Lotr1`,
        movie1: '',
        to2: `/Lotr2`,
        movie2: '',
        to3: `/Lotr3`,
        movie3: '',
        to4: `/Hobbit1`,
        movie4: '',
        to5: `/Hobbit2`,
        movie5: '',
        to6: `/Hobbit3`,
        movie6: ``,
        to7: `/warcraft`,
        movie7: `Warcraft, The Beginning`,
        h44: `King of Stormwind`,
        h4: `Liege Lord of Stormwind, Defender of Azeroth`,
        about: `Llane Wrynn I was the ruler of the Kingdom of Stormwind during the First War. He was the child of King Barathen Wrynn and Lady Varia, and the father of King Varian Wrynn. His grandson King Anduin Wrynn was given his middle name Llane to honor him.`,
        about1: ``,
        about2: ``,
    },

    {
        id: 65,
        race: 'dwarf',
        person: 'Pavel Ironfoot',
        warPic: 'pavel',
        to1: `/Lotr1`,
        movie1: 'The Fellowship of the Ring (2001)',
        to2: `/Lotr2`,
        movie2: 'The Two Towers (2002)',
        to3: `/Lotr3`,
        movie3: 'The Return of the King (2003)',
        to4: `/Hobbit1`,
        movie4: 'The Hobbit: An Unexpected Journey (2012)',
        to5: `/Hobbit2`,
        movie5: 'The Hobbit: The Desolation of Smaug (2013)',
        to6: `/Hobbit3`,
        movie6: `The Hobbit: The Battle of the Five Armies (2014)`,
        to7: `/warcraft`,
        movie7: `Warcraft, The Beginning`,
        h4: `blacksmith`,
        h44: `js senior`,
        about: `One of the greatest blacksmith of Khazad-dum and Iron-forge`,
        about1: `Brother of Dain Ironfoot and Muradin Bronzebeard.`,
        about2: `Very rich dwarf!`,
    },

    {
        id: 66,
        race: 'dwarf',
        person: `Dain II Ironfoot`,
        warPic: `dain`,
        to1: `/Lotr1`,
        movie1: '',
        to2: `/Lotr2`,
        movie2: '',
        to3: `/Lotr3`,
        movie3: '',
        to4: `/Hobbit1`,
        movie4: '',
        to5: `/Hobbit2`,
        movie5: '',
        to6: `/Hobbit3`,
        movie6: `The Hobbit: The Battle of the Five Armies (2014)`,
        to7: `/warcraft`,
        movie7: ``,
        h44: `Lord of the Iron Hills`,
        h4: `King of Durin's Folk, King under the Mountain`,
        about: `Dáin II Ironfoot (or King Dáin), the son of Náin and great-grandson of Dáin I of Durin's Folk. He was a Dwarven King of Durin's Folk, the fifth King under the Mountain, and the Lord of the Iron Hills during the War of the Ring in Middle-earth.`,
        about1: ``,
        about2: ``,
    },

    {
        id: 67,
        race: 'elf',
        person: `Thranduil`,
        warPic: `thranduil`,
        to1: `/Lotr1`,
        movie1: '',
        to2: `/Lotr2`,
        movie2: '',
        to3: `/Lotr3`,
        movie3: '',
        to4: `/Hobbit1`,
        movie4: '',
        to5: `/Hobbit2`,
        movie5: 'The Hobbit: The Desolation of Smaug (2013)',
        to6: `/Hobbit3`,
        movie6: `The Hobbit: The Battle of the Five Armies (2014)`,
        to7: `/warcraft`,
        movie7: ``,
        h44: `King of the Woodland Realm`,
        h4: `Elvenking`,
        about: `Thranduil, son of Oropher, was an Elven king who ruled over the Woodland Realm in the Third Age. Though inherently cautious, his army was key to victory in the Battle of Five Armies and he defended his realm against the forces of Sauron in the War of the Ring. He was the father of the Elven prince of Mirkwood, Legolas, who was a member of the Fellowship of the Ring.`,
        about1: `In The Hobbit, Thranduil is referred to only as the Elvenking.`,
        about2: ``,
    },

    {
        id: 68,
        race: 'ent',
        person: `Treebeard`,
        warPic: `treebeard`,
        to1: `/Lotr1`,
        movie1: '',
        to2: `/Lotr2`,
        movie2: 'The Two Towers (2002)',
        to3: `/Lotr3`,
        movie3: 'The Return of the King (2003)',
        to4: `/Hobbit1`,
        movie4: '',
        to5: `/Hobbit2`,
        movie5: '',
        to6: `/Hobbit3`,
        movie6: ``,
        to7: `/warcraft`,
        movie7: ``,
        h44: `Shepherd of the Trees`,
        h4: `Fangorn`,
        about: `Treebeard, also known as Fangorn, was the oldest of the Ents left in Middle-earth, an ancient tree-like being who was a "shepherd of trees". He had a very tall and stiff-limbed appearance, with bark-like skin and leafy hair.`,
        about1: `In Chapter 5 of The Two Towers, Gandalf calls Treebeard "...the oldest living thing that still walks beneath the Sun upon this Middle-earth." In The Return of the King, Chapter 6, "Many Partings", Celeborn addresses Treebeard as "Eldest."`,
        about2: ``,
    },
];

